[package]
name = "mybar-rs"
version = "0.1.0"
edition = "2024"

[dependencies]

[dependencies.xcb]
version = "1.5.0"

[dependencies.xcb-wm]
version = "0.4.0"
features = ["ewmh"]

# [dependencies.gtk]
# version = "0.9.6"
# package = "gtk4"
# features = ["v4_12"]

